proniashop-main/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.front.urls')),
    path('dashboard/', include('main.dashboard.urls')),
    path('auth/', include('main.auth.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proniashop-main/main/front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/<str:code>/', views.product_detail, name='product_detail'),
    path('category/<str:code>/', views.product_list, name='product_list'),
    path('carts/', views.carts, name='carts'),
    path('cart/<str:code>/', views.cart_detail, name='cart_detail'),
    path('add-to-cart/<str:code>', views.add_to_cart, name='add_to_cart'),
    path('active/cart/', views.active_cart, name='active_cart'),
    path('product_delete/<int:id>/',views.product_delete, name='product_delete'),
    path('wishlist',views.list_wishlist, name='wishlist'),
    path('remove-wishlist/<str:code>',views.remove_wishlist, name='remove_wishlist'),
    path('add-wishlist/<str:code>', views.add_wishlist, name='add_wishlist'),
    path('order-list',views.order_list, name='order_list'),
]

proniashop-main/main/front/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from main import models
import qrcode
from PIL import Image
from io import BytesIO
import base64


def index(request):
    categories = models.Category.objects.all()
    products = []
    reviews = models.Review.objects.all()

    if request.user.is_authenticated:
        liked_products = models.WishList.objects.filter(user=request.user).values_list('product_id', flat=True)
        for product in models.Product.objects.all():
            product.is_like = product.id in liked_products
            products.append(product)
    else:
        products = models.Product.objects.all()

    total_mark = sum(review.mark for review in reviews)
    mark = total_mark // len(reviews) if reviews else 0

    context = {
        'categories': categories,
        'products': products,
        'rating': range(1, 6),
        'mark': mark,
    }
    return render(request, 'front/index.html', context)


def product_detail(request,code):
    product = models.Product.objects.get(code=code)
    reviews = models.Review.objects.filter(product=product)
    images = models.ProductImg.objects.filter(product=product)
    liked = models.WishList.objects.filter(product=product,user=request.user).count() > 0
    mark = 0
    for i in reviews:
        mark += i.mark
    mark = int(mark/len(reviews)) if reviews else 0
    context = {
        'product':product,
        'mark':mark,
        'rating':range(1,6),
        'images':images,
        'reviews':reviews,
        'liked':liked,
    }
    return render(request, 'front/product/detail.html',context)

def product_list(request, code):
    products = []
    categories = models.Category.objects.all()

    if request.user.is_authenticated:
        liked_products = models.WishList.objects.filter(user=request.user).values_list('product_id', flat=True)
        for product in models.Product.objects.filter(category__code=code):
            product.is_like = product.id in liked_products
            products.append(product)
    else:
        products = models.Product.objects.filter(category__code=code)

    context = {
        'products': products,
        'categories': categories,
    }
    return render(request, 'front/category/product_list.html', context)


def product_delete(request,id):
    models.CartProduct.objects.get(id=id).delete()
    return redirect('front:active_cart')


def carts(request):
    queryset = models.Cart.objects.filter(user=request.user, status=4)
    context = {'queryset':queryset}
    return render(request, 'front/carts/list.html', context)


@login_required(login_url='auth:login')
def active_cart(request):
    queryset , _ = models.Cart.objects.get_or_create(user=request.user, status=1)
    return redirect('front:cart_detail', queryset.code)


@login_required(login_url='auth:login')
def cart_detail(request, code):
    cart = models.Cart.objects.get(code=code)
    queryset = models.CartProduct.objects.filter(cart=cart)
    if request.method == 'POST':
        data = list(request.POST.items())[1::]
        for id,value in data:
            cart_product = models.CartProduct.objects.get(id=id)
            cart_product.count = value
            cart_product.product.quantity -= int(value)
            cart.status = 2
            cart_product.product.save()
            cart.save()
            cart_product.save()
    context = {
        'cart': cart,
        'queryset':queryset
        }
    return render(request, 'front/carts/detail.html', context)


def add_to_cart(request,code):
    if models.Product.objects.filter(code=code):
        product = models.Product.objects.get(code=code)
        cart = models.Cart.objects.get(status=1, user=request.user)
        is_product = models.CartProduct.objects.filter(product=product,cart__status=1,cart__user=request.user).first()
        if is_product:
            is_product.count += 1
            is_product.save()
            return redirect('front:active_cart')
        if not cart:
            cart = models.Cart.objects.create(
                user=request.user,
                is_active=True
            )
        models.CartProduct.objects.create(
            product=product,
            cart=cart,
            count=1
        )
        return redirect('front:active_cart')
    return redirect('front:index')


@login_required(login_url='auth:login')
def list_wishlist(request):
    wishlists = models.WishList.objects.filter(user=request.user)
    context = {'wishlists':wishlists,}
    return render(request, 'front/wishlist/list.html',context) 


@login_required(login_url='auth:login')
def remove_wishlist(request,code):
    models.WishList.objects.get(user=request.user,product__code=code).delete()
    return redirect('front:wishlist')


@login_required(login_url='auth:login')
def add_wishlist(request,code):
    product = models.Product.objects.get(code=code)
    wish = models.WishList.objects.filter(product=product,user=request.user)
    if wish.count():
        return redirect('front:remove_wishlist',product.code)
    models.WishList.objects.create(product=product,user= request.user)
    return redirect('front:wishlist')


def order_list(request):
    ordered = models.CartProduct.objects.filter(cart__user=request.user, cart__status=2)
    returned = models.CartProduct.objects.filter(cart__user=request.user, cart__status=3)

    context = {
        'ordered': ordered,
        'returned': returned,
    }
    return render(request, 'front/order/list.html', context)

proniashop-main/templates/front/wishlist/list.html
{% extends 'front/base.html' %}
{% load static %}
{% block content %}
            <!-- Begin Main Content Area -->
            <main class="main-content">
                <div class="breadcrumb-area breadcrumb-height" data-bg-image="{% static 'front/images/breadcrumb/bg/1-1-1919x388.jpg' %}">
                    <div class="container h-100">
                        <div class="row h-100">
                            <div class="col-lg-12">
                                <div class="breadcrumb-item">
                                    <h2 class="breadcrumb-heading">Istaklar sahifasi</h2>
                                    <ul>
                                        <li>
                                            <a href="{% url 'front:index' %}">Bosh sahifa</a>
                                        </li>
                                        <li>Istaklar</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="wishlist-area section-space-y-axis-100">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <form action="javascript:void(0)">
                                    <div class="table-content table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="product_remove">o'chirish</th>
                                                    <th class="product-thumbnail">rasmlar</th>
                                                    <th class="cart-product-name">mahsulot</th>
                                                    <th class="product-price">asl narx</th>
                                                    <th class="product-stock-status">birja holati</th>
                                                    <th class="cart_btn">savatga qo'shish</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for wishlist in wishlists %}
                                                <tr>
                                                    <td class="product_remove">
                                                        <a href="{% url 'front:remove_wishlist' wishlist.product.code %}">
                                                            <i class="pe-7s-close" data-tippy="Remove" data-tippy-inertia="true"
                                                        data-tippy-animation="shift-away" data-tippy-delay="50"
                                                        data-tippy-arrow="true" data-tippy-theme="sharpborder"></i>
                                                        </a>
                                                    </td>
                                                    <td class="product-thumbnail">
                                                        <a href="{% url 'front:product_detail' wishlist.product.code %}">
                                                            <img src="{{wishlist.product.banner_img.url}}" alt="Wishlist Thumbnail" style="width: 200px;">
                                                        </a>
                                                    </td>
                                                    <td class="product-name"><a href="{% url 'front:product_detail' wishlist.product.code %}">{{wishlist.product.name}}</a></td>
                                                    {% if wishlist.product.discount_price %}
                                                        <td class="product-price"><span class="amount">{{wishlist.product.discount_price}} sum</span></td>
                                                    {% else %}
                                                        <td class="product-price"><span class="amount">{{wishlist.product.price}} sum</span></td>
                                                    {% endif %}
                                                    <td class="product-stock-status"><span class="in-stock">{{wishlist.product.stock_status}}</span></td>
                                                    <td class="cart_btn"><a href="{% url 'front:add_to_cart' wishlist.product.code %}">savatga qo'shish</a></td>
                                                </tr>                                                  
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <!-- Main Content Area End Here -->
{% endblock content %}